version: '3'
services:
  jupyterlab:
    build:
      context: .
      dockerfile: "Dockerfile"
    user: root
    volumes:
      - jupyterlab-dir:/home/JupyterLab/codes
    ports:
      - "8888:8888"
    environment:
      TZ: Asia/Tokyo
    command:
      jupyter lab
          --ip=0.0.0.0
          --allow-root
          --no-browser
          --NotebookApp.notebook_dir='/home/JupyterLab/codes'
          --NotebookApp.token='shipmmg_control'
volumes:
  jupyterlab-dir:
    driver_opts:
      type: none
      device: ./notebooks
      o: bind